CREATE SCHEMA IF NOT EXISTS DEVELOPERS_TEAM;
CREATE TABLE IF NOT EXISTS bills (
    id BIGINT NOT NULL AUTO_INCREMENT,
    docdate DATE NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS customers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    address VARCHAR (150),
    phone VARCHAR(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS developers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS managers (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    email VARCHAR (50),
    phone VARCHAR(20),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS projects (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    description VARCHAR (250),
    status VARCHAR(20),
    eta DATE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS qualifications (
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    responsibility VARCHAR (250),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tasks (
    id BIGINT NOT NULL AUTO_INCREMENT,
    title VARCHAR(50) NOT NULL,
    description VARCHAR (250),
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS works(
    id BIGINT NOT NULL AUTO_INCREMENT,
    name VARCHAR(50) NOT NULL,
    price DECIMAL (10,2),
    PRIMARY KEY (id)
);
